naming:
  FunctionNaming:
    ignoreAnnotated:
      - 'Composable'

complexity:
  TooManyFunctions:
    ignoreAnnotatedFunctions:
      - 'Preview'

style:
  MagicNumber:
    excludes:
      - '**/presentation/theme/Color.kt'

  UnusedPrivateMember:
    ignoreAnnotated:
      - 'Preview'
